server {
    listen       80;
    server_name  localhost;
    location /blog/ {
        root      /data/img;
        try_files $uri @default_avatar;
    }
    location /cset/ {
        root      /data/img;
        try_files $uri @default_avatar;
    }
    location /design/ {
        root      /data/img;
        try_files $uri @default_avatar;
    }
    location /pattern/ {
        root      /data/img;
        try_files $uri @default_avatar;
    }
    location /set/ {
        root      /data/img;
        try_files $uri @default_avatar;
    }
    location /showcase/ {
        root      /data/img;
        try_files $uri @default_avatar;
    }
    location /ui/ {
        root      /data/img;
        try_files $uri @default_avatar;
    }
    location /user/ {
        root      /data/img;
        try_files $uri @default_avatar;
    }
    location @default_avatar {
        root  /data/img;
        rewrite ^ /logo.svg break;
    }
    # This is for old images from posts.freesewing.org which are sadly lost
    location /uploads/ {
        root      /data/img;
        try_files $uri @default_avatar;
    }
    location @lost_image {
        root  /data/img;
        rewrite ^ /lost-image.svg break;
    }
    location / {
        return 403;
    }
}
