# FreeSewing sshd server configuration baseline

# Listen on ipv4 only
AddressFamily inet

# Ciphers and keying
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256

# Do not allow root logins over SSH
PermitRootLogin no

# Disallow password logins
PasswordAuthentication no

# Do not enable challenge-response passwords
KbdInteractiveAuthentication no

# Do not allow host-based authentication
HostbasedAuthentication no

# Only allow pubkey authentication
PubkeyAuthentication yes
AuthenticationMethods publickey

# Enbable PAM accounting
UsePAM yes

# Limit login attempts
MaxAuthTries 3

# Limit login timing
LoginGraceTime 30

# Client connection timeouts
ClientAliveInterval 300
ClientAliveCountMax 2

# Force SSH protocol 2 only
Protocol 2

# Do not allow X forwarding
X11Forwarding no

# Swallow MOTD
PrintMotd no

# No banner
Banner none

# Allow client to pass locale environment variables
AcceptEnv LANG LC_*

# override default of no subsystems
Subsystem       sftp    /usr/lib/openssh/sftp-server

# Limit login attempts
MaxAuthTries 3

# Limit login timing
LoginGraceTime 30

# Limit concurrent sessions
MaxSessions 2
MaxStartups 2:30:10



