# Debian firewall playbooks.
# For when all you want is to update the firewall config.
# This is faster than running the entire baseline playbook.
---
- name: Debian baseline playbook
  hosts: '!localhost'
  # Speed up playbook run by disabling facts gathering
  gather_facts: false
  tasks:
    # Include baseline tasks
    - name: Configure local firewall
      include_tasks: shared/debian.baseline.firewall.yaml
