# A reusable task to ensure a service is running and enabled on a debian 12 (bookworm) host
#
# To use this task, set the FSIAC_SYSTEMD_SERVICE variable to:
# - string: the name of the service to enable & start (.service suffix is optional)
# - array: a list of names of services to enable & start (.service suffix is optional)
#
# Maintainer: jdecock
#
---
- name: Make sure a systemd service unit is running (and enabled)
  become: true
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: "{{ item }}"
  # Support passing in both a string and an array
  loop: "{{ FSIAC_SYSTEMD_SERVICE if FSIAC_SYSTEMD_SERVICE is sequence and FSIAC_SYSTEMD_SERVICE is not string else [FSIAC_SYSTEMD_SERVICE] }}"
